//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interes
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_payments
    {
        public int item_id { get; set; }
        public int payment_id { get; set; }
        public int order_id { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
        public virtual payment payment { get; set; }
    }
}
